teststub.findContentAddress=http://localhost:8082/findcontent
teststub.sokVagValInfoAddress=http://localhost:8085/tak/teststub/SokVagvalsInfo/v2

#getaggregatedcaremanagers.v1.teststub.producerAddress=
#getaggregatedcaremanagers.v1.teststub.wsdlPath=
#getaggregatedcaremanagers.v1.teststub.serviceNamespace=
#getaggregatedcaremanagers.v1.teststub.serviceClass=
#getaggregatedcaremanagers.v1.teststub.portName=
#getaggregatedcaremanagers.v1.teststub.testDataGeneratorClass=
