<?xml version="1.0" encoding="UTF-8" ?>
<!-- Licensed to the Apache Software Foundation (ASF) under one or more contributor 
	license agreements. See the NOTICE file distributed with this work for additional 
	information regarding copyright ownership. Sveriges Kommuner och Landsting 
	licenses this file to you under the Apache License, Version 2.0 (the "License"); 
	you may not use this file except in compliance with the License. You may 
	obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 
	Unless required by applicable law or agreed to in writing, software distributed 
	under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES 
	OR CONDITIONS OF ANY KIND, either express or implied. See the License for 
	the specific language governing permissions and limitations under the License. -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:codes="urn:riv:coreprocess:residentparticipation:residentparticipation:enums:1"
	xmlns:tns="urn:riv:coreprocess:residentparticipation:residentparticipation:1"
	targetNamespace="urn:riv:coreprocess:residentparticipation:residentparticipation:1" elementFormDefault="qualified"
	attributeFormDefault="unqualified" version="1.0">

	<xs:import schemaLocation="coreprocess_residentparticipation_residentparticipation_enum_1.0.xsd"
		namespace="urn:riv:coreprocess:residentparticipation:residentparticipation:enums:1"/>

	<xs:complexType name="HeaderType">
		<xs:sequence>
			<xs:element name="accessControlHeader" type="tns:AccessControlHeaderType"/>
			<xs:element name="sourceSystemId" type="tns:IIType"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="AccessControlHeaderType">
		<xs:sequence>
			<xs:element name="accountableHealthcareProviderId" type="tns:IIType" />
			<xs:element name="accountableCareUnitId" type="tns:IIType" minOccurs="0"/>
			<xs:element name="patientId" type="tns:IIType"/>
			<xs:element name="careProcessId" type="tns:IIType" minOccurs="0"/>
			<xs:element name="blockComparisonTime" type="tns:TimeStampType"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="TimeStampType">
		<xs:annotation>
			<xs:documentation>
				A quantity specifying a point on the axis of natural time.
				A point in time is most often represented as a calendar
				expression.

				The time has the format YYYYMMDDhhmmss
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="(19|20)\d\d(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])(0[0-9]|1[0-9]|2[0123])([0-5])([0-9])([0-5])([0-9])"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="PractitionerType">
		<xs:sequence>
			<xs:element name="hsaId" type="tns:IIType"/>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element name="qualification" type="tns:CVType" minOccurs="0"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="CareTeamType">
		<xs:sequence>
			<xs:element name="id" type="tns:IIType"/>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="internalNotes" type="xs:string" minOccurs="0"/>
			<xs:element name="externalNotes" type="xs:string" minOccurs="0"/>
			<xs:element name="contact" type="tns:ContactType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="PractitionerRoleType">
		<xs:sequence>
			<xs:element name="careManagerHeader" type="tns:HeaderType"/>
			<xs:element name="code" type="tns:CVType"/>
			<xs:element name="practitioner" type="tns:PractitionerType"/>
			<xs:element name="careTeam" type="tns:CareTeamType" minOccurs="0"/>
			<xs:element name="period" type="tns:DatePeriodType"/>
			<xs:element name="internalNotes" type="xs:string" minOccurs="0"/>
			<xs:element name="externalNotes" type="xs:string" minOccurs="0"/>
			<xs:element name="managingCareGiver" type="tns:OrganizationType"/>
			<xs:element name="managingCareUnit" type="tns:OrganizationType" minOccurs="0" />
			<xs:element name="careProvidingCareUnit" type="tns:OrganizationType" minOccurs="0" />
			<xs:element name="contact" type="tns:ContactType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="OrganizationType">
		<xs:sequence>
			<xs:element name="hsaId" type="tns:IIType"/>
			<xs:element name="name" type="xs:string" minOccurs="0"/>
			<xs:element name="contact" type="tns:ContactType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ContactType">
		<xs:sequence>
			<xs:element name="telecom" type="tns:ContactPointSystemType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="address" type="tns:AddressType" minOccurs="0"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="AddressType">
		<xs:sequence>
			<xs:element name="type" type="tns:CVType" minOccurs="0"/>
			<xs:element name="line" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="city" type="xs:string" minOccurs="0"/>
			<xs:element name="postalCode" type="xs:string" minOccurs="0"/>
			<xs:element name="period" type="tns:HoursOfServiceType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ContactPointSystemType">
		<xs:sequence>
			<xs:element name="system" type="tns:CVType" minOccurs="0"/>
			<xs:element name="value" type="xs:string"/>
			<xs:element name="period" type="tns:HoursOfServiceType" minOccurs="0" maxOccurs="unbounded"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="DatePeriodType">
		<xs:sequence>
			<xs:element name="start" type="tns:DateType"/>
			<xs:element name="end" type="tns:DateType" minOccurs="0"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="HoursOfServiceType">
		<xs:sequence>
			<xs:element name="datePeriod" type="tns:DatePeriodType" minOccurs="0"/>
			<xs:element name="weekDay" type="codes:WeekDaysEnum" minOccurs="0" maxOccurs="7"/>
			<xs:element name="month" type="codes:MonthsEnum" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="time" type="tns:TimePeriodType" minOccurs="0"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:simpleType name="DateType">
		<xs:annotation>
			<xs:documentation>YYYYMMDD</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="(19|20)\d\d(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="TimeType">
		<xs:annotation>
			<xs:documentation>HHmmss</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-1][0-9]|2[0-3])[0-5][0-9][0-5][0-9]"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="TimePeriodType">
		<xs:annotation>
			<xs:documentation>
				Används för att specificera ett tidsintervall
				med hjälp av start- och sluttid.
				start:
				Starttid på formatet HHmmss
				end:
				Sluttid på formatet HHmmss
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="start" type="tns:TimeType" minOccurs="0"/>
			<xs:element name="end" type="tns:TimeType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
		
	<xs:complexType name="CVType">
		<xs:sequence>
			<xs:element name="code" type="xs:string" minOccurs="0"/>
			<xs:element name="codeSystem" type="xs:string" minOccurs="0"/>
			<xs:element name="codeSystemName" type="xs:string" minOccurs="0"/>
			<xs:element name="codeSystemVersion" type="xs:string" minOccurs="0"/>
			<xs:element name="displayName" type="xs:string" minOccurs="0"/>
			<xs:element name="originalText" type="xs:string" minOccurs="0"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="IIType">
		<xs:sequence>
			<xs:element name="root" type="xs:string"/>
			<xs:element name="extension" type="xs:string" minOccurs="0"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>
